apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: git@github.com:ariellev/v-manifest.git
    targetRevision: HEAD
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
