apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: git@github.com:ariellev/v-app.git
    targetRevision: v0.0.2
    helm:
      values: |
        ingress:
          host: 192.168.64.7.xip.io
        version: v3
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
